services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"

  books:
    build: ./BooksService
    container_name: books
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    restart: always
    expose:
      - "5001"
