services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"

  books:
    build: ./BooksService
    container_name: books
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    expose:
      - "5000"