name: Books Service CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Record start time
        run: echo "Start Time:$(date -Iminutes)" > /tmp/log.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: ./BooksService
          file: ./BooksService/Dockerfile
          tags: books:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: Check build status
        if: success()
        run: echo "image successfully built" >> /tmp/log.txt
      - name: Log build failure
        if: failure()
        run: echo "image not able to be built" >> /tmp/log.txt 
 
      - name: Upload Docker image and log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: books
          path: /tmp/image.tar

      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: /tmp/log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image and log
        uses: actions/download-artifact@v4    

      - name: Load Docker image
        run: docker load --input books/image.tar

      - name: Download log artifact
        uses: actions/download-artifact@v4
        with:
          name: log
          path: /tmp

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Check run status
        id: check_status
        run: echo "Container up and running" >> /tmp/log.txt

      - name: Log run failure
        if: failure()
        run: |
          echo "Container failed to run" >> /tmp/log.txt
          exit 1

      - name: Check container status
        run: docker ps

      - name: Set up Python
        if: steps.check_status.outcome == 'success'
        uses: actions/setup-python@v4
    
      - name: Install dependencies
        if: steps.check_status.outcome == 'success'
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        if: steps.check_status.outcome == 'success'
        run: |
          pytest -v ./tests/tests.py > tests_results.txt

      - name: Check pytest status
        if: steps.check_status.outcome == 'success' && success()
        run: echo "tests succeeded" >> /tmp/log.txt

      - name: Log pytest failure
        if: steps.check_status.outcome == 'success' && failure()
        run: echo "tests failed" >> /tmp/log.txt

      - name: Upload test results 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: |
            assn3_test_results.txt  

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: /tmp/log.txt
          overwrite: true
            
      - name: Tear down Docker Compose
        run: docker compose -f docker-compose.yml down

  query:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image and log
        uses: actions/download-artifact@v4
        
      - name: Load Docker image
        run: docker load --input books/image.tar

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d

      - name: Check container status
        run: docker ps

      - name: Curl POST requests
        run: |
          book1='{"title":"Adventures of Huckleberry Finn", "ISBN":"9780520343641", "genre":"Fiction"}'
          book2='{"title":"The Best of Isaac Asimov", "ISBN":"9780385050784", "genre":"Science Fiction"}'
          book3='{"title":"Fear No Evil", "ISBN":"9780394558783", "genre":"Biography"}'
          book6='{"title":"The Adventures of Tom Sawyer", "ISBN":"9780195810400", "genre":"Fiction"}'
          book7='{"title":"I, Robot", "ISBN":"9780553294385", "genre":"Science Fiction"}'
          book8='{"title":"Second Foundation", "ISBN":"9780553293364", "genre":"Science Fiction"}'
          sleep 10
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book1" http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book2" http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book3" http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book6" http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book7" http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book8" http://127.0.0.1:5001/books

      - name: Run query script
        run: python scripts/process_queries.py

      - name: Upload query results and log
        uses: actions/upload-artifact@v4
        with:
          name: query-response
          path: |
            response.txt
            log.txt

      - name: Tear down Docker Compose
        run: docker compose -f docker-compose.yml down